### PR TITLE
N+1 Performance Optimization and Integration Testing 🧪

### PR DESCRIPTION
**Pull request by jicamargo**
# 🚀 N+1 Performance Optimization and Integration Testing 🧪

## **Description** 📋
This PR 🔀 addresses the notorious N+1 problem in our Blogify application and spices things up with a dash of integration tests to ensure our app's views are in tip-top shape. 

**N+1 Problem Solution** 🛠️
We've triumphantly vanquished the N+1 problem by turbocharging our database queries. Before the fix, our application was a bit sluggish, bombarding the database with queries. We've meticulously analyzed those logs and applied the corrections. Now our app is faster and more efficient! 💨

*Before and After Screenshots* 📊
- **Before Fix**: 📸
image

- **After Fix**: 📸
image

**Integration Tests** 🧪
We've summoned the mighty Capybara to script comprehensive integration tests. These tests follow a logical flow to ensure our views are as robust as a suit of medieval armor.

***User Index Page*** 🧑‍💻
- ✔️ Verified that usernames of all users are displayed.
- ✔️ Confirmed the presence of profile pictures for each user.
- ✔️ Checked if the number of posts for each user is visible.
- ✔️ Verified redirection to a user's show page upon clicking their name.

***User Show Page*** 📖
- ✔️ Ensured the user's profile picture is visible.
- ✔️ Confirmed the display of the user's username.
- ✔️ Checked for the visibility of the number of posts the user has written.
- ✔️ Verified the display of the user's bio.
- ✔️ Checked for the presence of the user's first 3 posts.
- ✔️ Confirmed the presence of a button to view all of a user's posts.
- ✔️ Checked redirection to a user's post index page when clicking on a user's post.

***User Post Index Page*** 📝
- ✔️ Ensured the user's profile picture is visible.
- ✔️ Confirmed the display of the user's username.
- ✔️ Checked for the visibility of the number of posts the user has written.
- ✔️ Verified the display of a post's title.
- ✔️ Checked for the visibility of some of the post's body.
- ✔️ Confirmed the display of the first comments on a post.
- ✔️ Checked if the number of comments and likes on a post are visible.
- ✔️ Ensured that pagination is visible if there are more posts than fit on the view.
- ✔️ Verified redirection to a post's show page upon clicking on a post.

***Post Show Page*** 📝
- ✔️ Checked for the display of the post's title.
- ✔️ Verified the visibility of the post's author.
- ✔️ Checked for the visibility of the number of comments and likes on the post.
- ✔️ Ensured the display of the post body.
- ✔️ Checked for the presence of usernames of commenters.
- ✔️ Verified the display of each comment left by commenters.

**coding partners** 👁️‍🗨️
- @ibugithub  👀
- @gdumani  👀

Thank you for your attention and review. 🙏

Best regards, 🌟

### CODE REVIEW

**Review by laiifuu — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED :recycle: 

## Hi team :wave: 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

so-close


## Highlights
- [x] N+1 Problem solved :+1:
- [x] Integration tests added for all four pages :+1: 

## Required Changes ♻️
- [ ] It would be great if the tests actually succeed. After running them, all of them failed: 
image
Kindly fix this issue. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and :computer: Happy coding :computer: 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by jicamargo** [comment]
Hello @laiifuu, Thank for your review. It is very strange, because in my PC all the test passes well. 
For example this is the result of rspec spec/integration/user_show_spec.rb

image

Another partners had the same problem last week, and they have to send images of their processes.

What can I do? Could we connect via zoom to run the test with you?

**Comment by jicamargo** [comment]
I hope this message finds you well. I wanted to provide an update on the test results for this pull request. After thorough testing on my local development environment, I'm pleased to report that all tests have passed successfully.

I've attached a screenshot of the test results below for your reference:

image


## Thank you for your attention and help with this review.

**Review by Davidosky007 — APPROVED** [review]
Hi @jicamargo @ibugithub @gdumani 👋, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
* All tests passed 👍 
* Well written PR 👍 
* N +1 issue solved 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Pull request closed without merging**
